/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DiagnosticsRouteImport } from './routes/diagnostics'
import { Route as ExpensesRouteImport } from './routes/expenses'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as PartsRouteImport } from './routes/parts'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesNewRouteImport } from './routes/vehicles.new'
import { Route as VehiclesVehicleIdIndexRouteImport } from './routes/vehicles.$vehicleId.index'
import { Route as VehiclesVehicleIdEditRouteImport } from './routes/vehicles.$vehicleId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticsRoute = DiagnosticsRouteImport.update({
  id: '/diagnostics',
  path: '/diagnostics',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpensesRoute = ExpensesRouteImport.update({
  id: '/expenses',
  path: '/expenses',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const PartsRoute = PartsRouteImport.update({
  id: '/parts',
  path: '/parts',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesNewRoute = VehiclesNewRouteImport.update({
  id: '/vehicles/new',
  path: '/vehicles/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdIndexRoute = VehiclesVehicleIdIndexRouteImport.update({
  id: '/vehicles/$vehicleId/',
  path: '/vehicles/$vehicleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesVehicleIdEditRoute = VehiclesVehicleIdEditRouteImport.update({
  id: '/vehicles/$vehicleId/edit',
  path: '/vehicles/$vehicleId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/expenses': typeof ExpensesRoute
  '/maintenance': typeof MaintenanceRoute
  '/parts': typeof PartsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vehicles/new': typeof VehiclesNewRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/expenses': typeof ExpensesRoute
  '/maintenance': typeof MaintenanceRoute
  '/parts': typeof PartsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vehicles/new': typeof VehiclesNewRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/vehicles/$vehicleId': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/diagnostics': typeof DiagnosticsRoute
  '/expenses': typeof ExpensesRoute
  '/maintenance': typeof MaintenanceRoute
  '/parts': typeof PartsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/vehicles/new': typeof VehiclesNewRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/vehicles/$vehicleId/edit': typeof VehiclesVehicleIdEditRoute
  '/vehicles/$vehicleId/': typeof VehiclesVehicleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diagnostics'
    | '/expenses'
    | '/maintenance'
    | '/parts'
    | '/reports'
    | '/settings'
    | '/vehicles/new'
    | '/vehicles/'
    | '/vehicles/$vehicleId/edit'
    | '/vehicles/$vehicleId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diagnostics'
    | '/expenses'
    | '/maintenance'
    | '/parts'
    | '/reports'
    | '/settings'
    | '/vehicles/new'
    | '/vehicles'
    | '/vehicles/$vehicleId/edit'
    | '/vehicles/$vehicleId'
  id:
    | '__root__'
    | '/'
    | '/diagnostics'
    | '/expenses'
    | '/maintenance'
    | '/parts'
    | '/reports'
    | '/settings'
    | '/vehicles/new'
    | '/vehicles/'
    | '/vehicles/$vehicleId/edit'
    | '/vehicles/$vehicleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DiagnosticsRoute: typeof DiagnosticsRoute
  ExpensesRoute: typeof ExpensesRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PartsRoute: typeof PartsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  VehiclesNewRoute: typeof VehiclesNewRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  VehiclesVehicleIdEditRoute: typeof VehiclesVehicleIdEditRoute
  VehiclesVehicleIdIndexRoute: typeof VehiclesVehicleIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostics': {
      id: '/diagnostics'
      path: '/diagnostics'
      fullPath: '/diagnostics'
      preLoaderRoute: typeof DiagnosticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expenses': {
      id: '/expenses'
      path: '/expenses'
      fullPath: '/expenses'
      preLoaderRoute: typeof ExpensesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parts': {
      id: '/parts'
      path: '/parts'
      fullPath: '/parts'
      preLoaderRoute: typeof PartsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/new': {
      id: '/vehicles/new'
      path: '/vehicles/new'
      fullPath: '/vehicles/new'
      preLoaderRoute: typeof VehiclesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId/': {
      id: '/vehicles/$vehicleId/'
      path: '/vehicles/$vehicleId'
      fullPath: '/vehicles/$vehicleId/'
      preLoaderRoute: typeof VehiclesVehicleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$vehicleId/edit': {
      id: '/vehicles/$vehicleId/edit'
      path: '/vehicles/$vehicleId/edit'
      fullPath: '/vehicles/$vehicleId/edit'
      preLoaderRoute: typeof VehiclesVehicleIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DiagnosticsRoute: DiagnosticsRoute,
  ExpensesRoute: ExpensesRoute,
  MaintenanceRoute: MaintenanceRoute,
  PartsRoute: PartsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  VehiclesNewRoute: VehiclesNewRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  VehiclesVehicleIdEditRoute: VehiclesVehicleIdEditRoute,
  VehiclesVehicleIdIndexRoute: VehiclesVehicleIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
